### ISSUE TITLE
An API token is required to use Mapbox GL

### ISSUE THREAD

**Issue by profaneblood** [thallada/modmapper-web#1]
Whenever I try to run a local version of this app, the map doesn't display and if I zoom in too much I get that unhandled error. What should I do? Do I need to add an API token and if so, how can I do this? Thanks.

**Comment by thallada** [comment]
I forgot to include instructions for that in the readme. You'll want to create a file named `.env` at the root of the project with the contents:

```
NEXT_PUBLIC_MAPBOX_TOKEN=tokengoeshere
```

You can get a token by [creating a mapbox account and generating a token on the access token page](https://docs.mapbox.com/help/glossary/access-token/).

Then restart the dev server.

**Comment by thallada** [comment]
Just updated the readme with these instructions. Feel free to reopen if that didn't fix it for you.
