### ISSUE TITLE
Enhancement: compare on map few choosen mods. 

### ISSUE THREAD

**Issue by seachdamh** [thallada/modmapper-web#2]
First: This mod conflict map is really great.

What I missing: In ui I want to specify a few mods by name to see changes they made. Not whole list of 100+ mods in my game or all mods in the world but for example "Anna npcs" with "The Mystery of Pine Lake" and "Hjertesten Hall - Player Home and Settlement" to see potential conflicts (and mayby think about patches)

**Comment by thallada** [comment]
You are now able to search for mods and then add plugins within them to the list and see conflicts from that list on the map.
